name: Offeringo Landing Page
favicon: null
layout_spectrum: 0.6175205598119646
typography_spectrum: 0.9339139538351446
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f5f5'
    - '#dd6e0b'
    - '#000000'
    - '#00ffff'
    - '#0080ff'
  brandStrength: 0.30724245426245034
  lightness: 0.37867315276525915
  saturation: 0.37839018553495407
  rhythmicContrast: 0.37947424594312906
purpose: []
