layout_spectrum: 0.6175205598119646
favicon: null
name: Offeringo Landing Page
purpose: []
analytics:
  facebook: null
  google: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  version: null
  bucket: null
color:
  brandStrength: 1
  lightness: 0.3786731527652591
  saturation: 0.3783901855349541
  rhythmicContrast: 0.3794742459431291
  brandColors:
    - '#f5f5f5'
    - '#dd6e0b'
    - '#000000'
    - '#00ffff'
    - '#0080ff'
typography_spectrum: 0.9339139538351446
